name: Tests
on: [push, pull_request]

jobs:
    unit-component:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Run unit tests
              run: npm run test:unit
              continue-on-error: false

            - name: Run component tests
              run: npm run test:component
              continue-on-error: true # Allow some failures while we fix them

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: unit-component-results
                  path: test-reports/

    integration:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Run integration tests
              run: npm run test:integration
              continue-on-error: true # Allow failures while we fix Request issues
              env:
                  NODE_ENV: test

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: integration-results
                  path: test-reports/

    e2e:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright browsers
              run: npx playwright install chromium --with-deps

            - name: Wait for Netlify Deploy Preview
              run: node scripts/wait-for-deploy.js --timeout=600
              env:
                  GITHUB_PR_NUMBER: ${{ github.event.number }}
                  GITHUB_REPOSITORY: ${{ github.repository }}

            - name: Get Deploy URL
              id: deploy-url
              run: |
                  if [ -n "${{ github.event.number }}" ]; then
                    DEPLOY_URL="https://deploy-preview-${{ github.event.number }}--spaghettis.netlify.app"
                  else
                    DEPLOY_URL="https://spaghettis.netlify.app"
                  fi
                  echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
                  echo "Deploy URL: $DEPLOY_URL"

            - name: Run E2E Tests (Playwright)
              run: |
                  if [ -f "tests/e2e/playwright.config.ci.js" ]; then
                    echo "Running Playwright E2E tests"
                    npx playwright test --config=tests/e2e/playwright.config.ci.js
                  elif [ -f "playwright.config.js" ]; then
                    echo "Using root playwright config"
                    npx playwright test
                  else
                    echo "No Playwright E2E config found"
                  fi
              env:
                  BASE_URL: ${{ steps.deploy-url.outputs.url }}
              continue-on-error: true

            - name: Run Cucumber E2E Tests
              run: npm run test:cucumber:all
              env:
                  BASE_URL: ${{ steps.deploy-url.outputs.url }}
                  CI: true
              continue-on-error: true

            - name: Run Cypress E2E Tests
              run: npm run test:cypress
              env:
                  BASE_URL: ${{ steps.deploy-url.outputs.url }}
                  GITHUB_PR_NUMBER: ${{ github.event.number }}
                  CI: true
              continue-on-error: true

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: e2e-results
                  path: |
                      test-results/
                      playwright-report/
                      test-reports/cucumber-report.*
                      test-reports/cypress/
